import uuid
from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

from database import init_db, log_submission, get_all_logs, get_log_by_id, submit_appeal
from detector import detect_signal_llm, detect_signal_stylometrics, calculate_confidence

app = Flask(__name__)

# Initialize database tables
init_db()

# Setup rate limiting with in-memory storage
limiter = Limiter(
    key_func=get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://"
)

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json(silent=True)
    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Missing required fields: 'text' and 'creator_id' must be provided."}), 400
    
    text = data["text"]
    creator_id = data["creator_id"]
    
    if not text.strip() or not creator_id.strip():
        return jsonify({"error": "Fields 'text' and 'creator_id' cannot be empty."}), 400

    # 1. Run LLM signal analysis
    llm_result = detect_signal_llm(text)
    llm_score = llm_result["score"]
    
    # 2. Run Stylometric signal analysis
    sty_score = detect_signal_stylometrics(text)
    
    # 3. Combine scores into an ensemble confidence score
    confidence = round(calculate_confidence(llm_score, sty_score), 4)
    
    # 4. Map confidence to calibrated thresholds
    if confidence < 0.40:
        attribution = "likely_human"
        label = "Verified Human: This content exhibits natural stylistic variations and structural characteristics consistent with original human writing."
    elif confidence <= 0.70:
        attribution = "uncertain"
        label = "Unverified: The stylistic evaluation of this content is inconclusive. It may contain a blend of human and assisted writing."
    else:
        attribution = "likely_ai"
        label = "AI-Generated: This content matches patterns and structural markers highly characteristic of text generated by artificial intelligence."
        
    # 5. Generate unique content_id
    content_id = str(uuid.uuid4())
    
    # 6. Log the submission with both scores in SQLite database
    log_submission(
        content_id=content_id,
        creator_id=creator_id,
        text=text,
        attribution=attribution,
        confidence=confidence,
        llm_score=llm_score,
        stylometric_score=sty_score
    )
    
    # 7. Return response
    return jsonify({
        "content_id": content_id,
        "creator_id": creator_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
        "status": "classified"
    })

@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json(silent=True)
    if not data or "content_id" not in data or "creator_reasoning" not in data:
        return jsonify({"error": "Missing required fields: 'content_id' and 'creator_reasoning' must be provided."}), 400
        
    content_id = data["content_id"]
    creator_reasoning = data["creator_reasoning"]
    
    if not content_id.strip() or not creator_reasoning.strip():
        return jsonify({"error": "Fields 'content_id' and 'creator_reasoning' cannot be empty."}), 400
        
    # Check if the log entry exists first
    log_entry = get_log_by_id(content_id)
    if not log_entry:
        return jsonify({"error": f"Content submission with ID {content_id} not found."}), 404
        
    # Update status to under_review and store reasoning
    success = submit_appeal(content_id, creator_reasoning)
    if not success:
        return jsonify({"error": "Failed to process appeal."}), 500
        
    return jsonify({
        "message": "Appeal successfully received and logged.",
        "content_id": content_id,
        "status": "under_review"
    })

@app.route("/log", methods=["GET"])
def get_logs():
    entries = get_all_logs()
    return jsonify({"entries": entries})

if __name__ == "__main__":
    app.run(port=5000, debug=True)
