from groq import Groq
import json
import traceback
from config import GROQ_API_KEY, LLM_MODEL

_client = None

def _get_client():
    global _client
    if _client is None:
        if not GROQ_API_KEY:
            raise ValueError("GROQ_API_KEY is not set in environment.")
        _client = Groq(api_key=GROQ_API_KEY)
    return _client

def detect_signal_llm(text: str) -> dict:
    """
    Evaluates the input text using the Groq LLM to estimate the probability 
    that it was generated by an AI model.
    
    Returns a dict with:
      - "score" : float (0.0 to 1.0, where 1.0 is highly likely AI)
      - "reasoning" : str (brief explanation of the evaluation)
    """
    if not text or not text.strip():
        return {"score": 0.0, "reasoning": "Empty text provided."}

    system_prompt = (
        "You are an expert AI content detection assistant. Analyze the user's submitted text "
        "and determine whether it was written by a human or generated by an AI (such as Llama, Claude, or GPT).\n\n"
        "Analyze features like clichés, repetitive structures, predictable transitions, "
        "and overall semantic flavor.\n\n"
        "You MUST return a JSON object with exactly two keys:\n"
        '- "score": a floating-point number between 0.0 and 1.0 (where 0.0 is 100% human-written, and 1.0 is 100% AI-generated).\n'
        '- "reasoning": a brief one or two-sentence explanation for your rating.\n\n'
        "Format your entire response as a valid JSON object."
    )
    
    user_prompt = f"Analyze this text:\n\n{text}"
    
    try:
        client = _get_client()
        response = client.chat.completions.create(
            model=LLM_MODEL,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.0,
            response_format={"type": "json_object"}
        )
        content = response.choices[0].message.content
        data = json.loads(content)
        
        score = float(data.get("score", 0.5))
        reasoning = str(data.get("reasoning", "Parsed from LLM response."))
        
        # Clamp score between 0.0 and 1.0
        score = max(0.0, min(1.0, score))
        
        return {"score": score, "reasoning": reasoning}
    except Exception as e:
        print(f"Error in detect_signal_llm: {e}")
        traceback.print_exc()
        return {"score": 0.5, "reasoning": f"Failed to execute LLM classification: {str(e)}"}

def detect_signal_stylometrics(text: str) -> float:
    """
    Placeholder for stylometric complexity analysis. 
    Will be fully implemented in Milestone 4.
    """
    return 0.5
