from groq import Groq
import json
import traceback
from config import GROQ_API_KEY, LLM_MODEL

_client = None

def _get_client():
    global _client
    if _client is None:
        if not GROQ_API_KEY:
            raise ValueError("GROQ_API_KEY is not set in environment.")
        _client = Groq(api_key=GROQ_API_KEY)
    return _client

def detect_signal_llm(text: str) -> dict:
    """
    Evaluates the input text using the Groq LLM to estimate the probability 
    that it was generated by an AI model.
    
    Returns a dict with:
      - "score" : float (0.0 to 1.0, where 1.0 is highly likely AI)
      - "reasoning" : str (brief explanation of the evaluation)
    """
    if not text or not text.strip():
        return {"score": 0.0, "reasoning": "Empty text provided."}

    system_prompt = (
        "You are an expert AI content detection assistant. Analyze the user's submitted text "
        "and determine whether it was written by a human or generated by an AI (such as Llama, Claude, or GPT).\n\n"
        "Analyze features like clichés, repetitive structures, predictable transitions, "
        "and overall semantic flavor.\n\n"
        "You MUST return a JSON object with exactly two keys:\n"
        '- "score": a floating-point number between 0.0 and 1.0 (where 0.0 is 100% human-written, and 1.0 is 100% AI-generated).\n'
        '- "reasoning": a brief one or two-sentence explanation for your rating.\n\n'
        "Format your entire response as a valid JSON object."
    )
    
    user_prompt = f"Analyze this text:\n\n{text}"
    
    try:
        client = _get_client()
        response = client.chat.completions.create(
            model=LLM_MODEL,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.0,
            response_format={"type": "json_object"}
        )
        content = response.choices[0].message.content
        data = json.loads(content)
        
        score = float(data.get("score", 0.5))
        reasoning = str(data.get("reasoning", "Parsed from LLM response."))
        
        # Clamp score between 0.0 and 1.0
        score = max(0.0, min(1.0, score))
        
        return {"score": score, "reasoning": reasoning}
    except Exception as e:
        print(f"Error in detect_signal_llm: {e}")
        traceback.print_exc()
        return {"score": 0.5, "reasoning": f"Failed to execute LLM classification: {str(e)}"}

def detect_signal_stylometrics(text: str) -> float:
    """
    Computes a composite stylometric score [0.0 - 1.0] using two structural metrics:
      1. Sentence Length Variance Score (S_var = e^(-var / 50.0))
      2. Type-Token Ratio Score (S_ttr = max(0.0, 1.0 - TTR / 0.65))
      
    Returns the composite score S_sty = 0.6 * S_var + 0.4 * S_ttr.
    """
    import re
    import math
    
    if not text or not text.strip():
        return 0.5

    # 1. Sentence Length Variance
    # Split text into sentences using basic sentence boundary punctuation (. ! ?)
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    
    sentence_lengths = []
    for s in sentences:
        words = s.split()
        if words:
            sentence_lengths.append(len(words))
            
    if not sentence_lengths:
        s_var = 0.5
    else:
        n = len(sentence_lengths)
        mean_len = sum(sentence_lengths) / n
        if n > 1:
            variance = sum((x - mean_len) ** 2 for x in sentence_lengths) / n
        else:
            variance = 0.0
            
        s_var = math.exp(-variance / 50.0)

    # 2. Type-Token Ratio (TTR)
    # Clean text to remove punctuation and convert to lowercase
    cleaned_text = re.sub(r'[^\w\s]', '', text.lower())
    words = cleaned_text.split()
    
    # Restrict to first 200 words to avoid text length bias
    words_subset = words[:200]
    total_tokens = len(words_subset)
    
    if total_tokens == 0:
        s_ttr = 0.5
    else:
        unique_tokens = len(set(words_subset))
        ttr = unique_tokens / total_tokens
        s_ttr = max(0.0, 1.0 - (ttr / 0.65))

    # 3. Composite score
    s_sty = 0.6 * s_var + 0.4 * s_ttr
    # Clamp to ensure it falls strictly in [0.0, 1.0]
    return max(0.0, min(1.0, s_sty))

def calculate_confidence(llm_score: float, sty_score: float) -> float:
    """
    Combines LLM score and Stylometric score using a weighted average.
      C = 0.7 * S_llm + 0.3 * S_sty
    """
    return 0.7 * llm_score + 0.3 * sty_score

